# Generated by Django 6.0.1 on 2026-02-03 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('subscription_type', models.CharField(choices=[('Basic', 'Basic - Gym Access Only'), ('Premium', 'Premium - Gym + Classes'), ('Elite', 'Elite - Gym + Classes + Personal Trainer')], default='Basic', max_length=20)),
                ('subscription_status', models.BooleanField(default=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
